/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package informationsecurity;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.crypto.Cipher;
import javax.crypto.CipherOutputStream;
import javax.crypto.NoSuchPaddingException;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.UIManager;

/**
 *
 * @author Aman Kuvera
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    AesAlgorithm aesAlgo;
    DesAlgorithm DesAlgo;
    
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(16, 0), new java.awt.Dimension(16, 0), new java.awt.Dimension(16, 32767));
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        preview = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        filePath = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        logsBox = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Algorithm = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        secKey = new javax.swing.JTextField();
        jpb1 = new javax.swing.JProgressBar();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jta1 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jta2 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jButton7 = new javax.swing.JButton();
        jcb1 = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        uk1 = new javax.swing.JTextField();
        jpb2 = new javax.swing.JProgressBar();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        help = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 2, 2, new java.awt.Color(51, 0, 0)));

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ENCRYPT - O - PEDIA");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "by AK DEV.", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Tahoma", 0, 10))); // NOI18N

        jPanel2.setBackground(java.awt.SystemColor.windowBorder);
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Image Encrypter and Decrypter ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        preview.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        preview.setText("Image Preview");
        preview.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jButton1.setText("Change");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        filePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filePathActionPerformed(evt);
            }
        });

        logsBox.setEditable(false);
        logsBox.setColumns(20);
        logsBox.setRows(5);
        jScrollPane1.setViewportView(logsBox);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Encryption / Decryption Logs :");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Control Panel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jLayeredPane1.setForeground(new java.awt.Color(255, 255, 255));

        jButton3.setText("Decrypt");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select An Algorithm For Encryption / Decryption :");

        Algorithm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "AES", "DES" }));
        Algorithm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlgorithmActionPerformed(evt);
            }
        });

        jButton2.setText("Encrypt");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Save As :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Secret Key :");

        jpb1.setForeground(new java.awt.Color(255, 51, 51));
        jpb1.setToolTipText("Cryption Status");
        UIManager.put("ProgressBar.background", Color.ORANGE);
        UIManager.put("ProgressBar.foreground", Color.BLUE);
        UIManager.put("ProgressBar.selectionBackground", Color.RED);
        UIManager.put("ProgressBar.selectionForeground", Color.GREEN);

        jLayeredPane1.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Algorithm, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(name, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(secKey, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jpb1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(name))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Algorithm, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 82, Short.MAX_VALUE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(secKey)
                        .addGap(18, 18, 18)
                        .addComponent(jpb1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Algorithm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpb1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(secKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jButton5.setText("Clear Logs");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Save Logs");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(filePath)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(preview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filePath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(preview, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        jPanel4.setBackground(java.awt.SystemColor.windowBorder);
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Text Encrypter and Decrypter ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        jta1.setColumns(20);
        jta1.setRows(5);
        jta1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(jta1);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Input Text :");

        jta2.setColumns(20);
        jta2.setRows(5);
        jta2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jScrollPane5.setViewportView(jta2);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Encrypted / Decrypted Text :");

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Control Panel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        jButton7.setText("Decrypt");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jcb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "AES", "DES" }));
        jcb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb1ActionPerformed(evt);
            }
        });

        jButton8.setText("Clear All");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton4.setText("Encrypt");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Select and algorithm for Encryption / Decryption :");

        jButton9.setText("Save ");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Secret Key:");

        uk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uk1ActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(jButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jcb1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jButton8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jButton9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(uk1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jpb2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uk1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpb2, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcb1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(uk1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpb2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addContainerGap())
        );

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("© 2020.14.05.v01.00 Coded and Designed as Kuvera_Aman");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLayeredPane2))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(java.awt.SystemColor.windowBorder);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("TOOL GUIDE");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.windowBorder, 2));

        help.setEditable(false);
        help.setColumns(20);
        help.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        help.setRows(5);
        help.setText("For Help regarding each tool, Refer the Menu Bar.\n=================================================\n\nHelp ShortCuts:\n\nImage Encrypter - CTRL + I.\n\nText Encrypter - CTRL + T.\n\n=================================================\n\nFor more Information regarding the Developer click on the\n\"About Me\" in the Menu Bar.\n\n\nUse the Logs to recall which file you just encrypted / \nDecrypted. And Save the logs for future Use.");
        jScrollPane4.setViewportView(help);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel4.getAccessibleContext().setAccessibleDescription("");

        jMenuBar1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 0, 2, new java.awt.Color(0, 0, 0)));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setFocusCycleRoot(true);
        jMenuBar1.setInheritsPopupMenu(true);
        jMenuBar1.setMargin(new java.awt.Insets(1, 1, 1, 1));

        jMenu1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, java.awt.SystemColor.controlHighlight));
        jMenu1.setText("      Tool Guide      ");
        jMenu1.setToolTipText("Save to Custom Location");
        jMenu1.setBorderPainted(true);
        jMenu1.setFocusPainted(true);
        jMenu1.setName(""); // NOI18N
        jMenu1.setOpaque(true);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Image Tool");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Text Tool");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, java.awt.SystemColor.controlHighlight));
        jMenu2.setText("       Contact Me      ");
        jMenu2.setToolTipText("Read About the Developer");
        jMenu2.setBorderPainted(true);
        jMenu2.setFocusPainted(true);
        jMenu2.setOpaque(true);
        jMenu2.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu2MenuSelected(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleParent(jFrame1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uk1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uk1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String path = "C:\\Users\\Aman Kuvera\\Desktop\\ISS\\Text_Encrypt_Decrypt.txt";
        DateFormat date = new SimpleDateFormat("[yyyy/MM/dd] [HH:mm:ss]");
        Date d = new Date();
        String DT = date.format(d);
        String uk = uk1.getText();
        String algo = jcb1.getSelectedItem().toString();
            if(uk.equals("")){
                if(algo.equals("AES"))
                    uk = "Aman-Kuvera1999!";
                else
                    uk = "Kuvera99";
            }
        String text = DT+"\n\nSimple Text:\n"+jta1.getText()+"\n\nEncrypted/Decrypted Text:\n"+jta2.getText()+"\n\nKey: "+uk+"\n\nAlgorithm:"+ algo + "\n\n\n" ;

        try {
            FileWriter fw = new FileWriter(path, true);
            fw.write(text);
            fw.close();
            JOptionPane.showMessageDialog(null, "Logs Saved Successfully \n Path :"+path);
        }
        catch(IOException e) {
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String path = "C:\\Users\\Aman Kuvera\\Desktop\\ISS\\Logs.txt";
        DateFormat date = new SimpleDateFormat("[yyyy/MM/dd] [HH:mm:ss]");
        Date d = new Date();
        String DT = date.format(d);
        String text = DT+"\n"+logsBox.getText() + "\n"+"\n" ;

        try {
            FileWriter fw = new FileWriter(path, true);
            fw.write(text);
            fw.close();
            JOptionPane.showMessageDialog(null, "Logs Saved Successfully \n Path :"+path);
        }
        catch(IOException e) {
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int response = JOptionPane.showConfirmDialog(null,"Are you sure you want to clear all logs?","Clear Logs Confirmation",JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(response == JOptionPane.YES_OPTION)
        {
            logsBox.setText(null);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{

            String algo = Algorithm.getSelectedItem().toString();
            jpb1.setValue(10);
            if("Select".equals(algo)){
                JOptionPane.showMessageDialog(null,"Please Select and algorithm to encrypt");
                jpb1.setValue(0);
            }
            else{
                FileInputStream file = new FileInputStream(filePath.getText());
                String encpath = "C:\\Users\\Aman Kuvera\\Desktop\\ISS\\"+name.getText()+"Encrypt.jpg";
                jpb1.setValue(20);
                FileOutputStream outStream = new FileOutputStream(encpath);
                byte k[] = null;
                String userKey = secKey.getText();
                jpb1.setValue(30);
                if("DES".equals(algo))
                {
                    if(userKey.equals("")){
                        userKey = "Kuvera99";
                        k = userKey.getBytes();
                        jpb1.setValue(40);
                    }
                    else if(userKey.length()!=8){
                        JOptionPane.showMessageDialog(null,"The key length for DES should be exactly 8");
                        jpb1.setValue(0);
                    }
                    else{
                    k= userKey.getBytes();
                    jpb1.setValue(40);
                    }
                }
                else{
                    if(userKey.equals("")){
                        userKey = "Aman-Kuvera1999!";
                        k = userKey.getBytes();
                        jpb1.setValue(40);
                    }
                    else if(userKey.length()!=16){
                        jpb1.setValue(40);
                        JOptionPane.showMessageDialog(null,"The key length for AES should be exactly 16");
                        jpb1.setValue(0);
                    }
                    else{
                    k= userKey.getBytes();
                    jpb1.setValue(40);
                    }

                }

                SecretKeySpec key = new SecretKeySpec(k,algo);
                Cipher enc = Cipher.getInstance(algo);
                enc.init(Cipher.ENCRYPT_MODE,key);
                CipherOutputStream cos = new CipherOutputStream(outStream,enc);            
                byte buf[] = new byte[1024];
                int read;
                jpb1.setValue(90);
                JOptionPane.showMessageDialog(null,"The file was encrypted Successfully using "+algo);
                logsBox.append("Encrypt -> "+ algo+"/"+userKey +" " + filePath.getText()+'\n');
//                filePath.setText(encpath);
                jpb1.setValue(0);
                while((read=file.read(buf))!=1){
                    cos.write(buf,0,read);
                }              
                file.close();
                outStream.flush();
                cos.close();
                jpb1.setValue(0);
            }

        }
        catch(HeadlessException | IOException | InvalidKeyException | NoSuchAlgorithmException | NoSuchPaddingException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void AlgorithmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlgorithmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlgorithmActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            String algo = Algorithm.getSelectedItem().toString();
            jpb1.setValue(10);
            if("Select".equals(algo)){
                JOptionPane.showMessageDialog(null,"Please Select and algorithm to decrypt");
                jpb1.setValue(0);
            }
            else{
                FileInputStream file = new FileInputStream(filePath.getText());
                String decpath = "C:\\Users\\Aman Kuvera\\Desktop\\ISS\\"+name.getText()+"Decrypt.jpg";
                jpb1.setValue(20);
                FileOutputStream outStream = new FileOutputStream(decpath);
                byte k[] = null;
                String userKey = secKey.getText();
                jpb1.setValue(30);
                if("DES".equals(algo))
                {
                    if(userKey.equals("")){
                        userKey = "Kuvera99";
                        k = userKey.getBytes();
                        jpb1.setValue(40);
                    }
                    else if(userKey.length()!=8){
                        JOptionPane.showMessageDialog(null,"The key length for DES should be exactly 8");
                        jpb1.setValue(0);
                    }
                    else{
                    k= userKey.getBytes();
                    jpb1.setValue(40);
                    }
                }
                else{
                    if(userKey.equals("")){
                        userKey = "Aman-Kuvera1999!";
                        k = userKey.getBytes();
                        jpb1.setValue(40);
                    }
                    else if(userKey.length()!=16){
                        jpb1.setValue(40);
                        JOptionPane.showMessageDialog(null,"The key length for AES should be exactly 16");
                        jpb1.setValue(0);
                    }
                    else{
                    k= userKey.getBytes();
                    jpb1.setValue(40);
                    }

                }
                SecretKeySpec key = new SecretKeySpec(k,algo);
                Cipher enc = Cipher.getInstance(algo);
                enc.init(Cipher.DECRYPT_MODE,key);
                CipherOutputStream cos = new CipherOutputStream(outStream,enc);
                byte buf[] = new byte[1024];
                int read;
                jpb1.setValue(90);
                JOptionPane.showMessageDialog(null,"The file was Decrypted Successfully");
                logsBox.append("Decrypt -> "+ algo +" " + filePath.getText()+'\n');
                jpb1.setValue(0);
//                filePath.setText(decpath);
                while((read=file.read(buf))!=1){
                    cos.write(buf,0,read);

                }
                
                file.close();
                outStream.flush();
                cos.close();
                jpb1.setValue(0);
            }

        }
        catch(HeadlessException | IOException | InvalidKeyException | NoSuchAlgorithmException | NoSuchPaddingException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void filePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filePathActionPerformed

    }//GEN-LAST:event_filePathActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JFileChooser chooser = new JFileChooser("C:\\Users\\Aman Kuvera\\Desktop\\ISS");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("i Extension supported","jpg","jpeg","png");
        chooser.setFileFilter(filter);
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String sIm = f.getAbsolutePath();
        filePath.setText(sIm);
        preview.setText(null);
        ImageIcon imIco = new ImageIcon(sIm);
        Image imFit = imIco.getImage();
        Image imgFit = imFit.getScaledInstance(preview.getWidth(), preview.getHeight(), Image.SCALE_SMOOTH);
        preview.setIcon(new ImageIcon(imgFit));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        help.setText("Image Encrypter and Decrypter:\n" +
"===============================================\n" +
"Step 1: Select and Image File using \"Change\"\n" +
"\n" +
"Step 2: \"Image Preview\" area shows the Image\n" +
"\n" +
"Step 3: The Control Panel help to control the tool's actions.\n" +
"\n" +
"Step 4: Select the Algorithm to be used for\n" +
"	encryption/decryption.\n" +
"\n" +
"Step 5: The Secret key field should be given the prefered key \n" +
"	for encryption.\n" +
"\n" +
"-----------------------------------------------------------------------------------\n" +
"\n" +
">>Secret Key should be of length of 8 - DES.\n" +
">>Secret Key should be of length of 16 - AES.\n" +
">>If a Secret Key is not provided by User,the default Key is \n" +
"  used.\n" +
"\n" +
"-----------------------------------------------------------------------------------\n" +
"\n" +
"Step 6: Enter the Name for the Encrypted / Decrypted file to \n" +
"Save As in the set location and click on Encrypt to Save the \n" +
"file with given name.\n" +
"\n" +
"..............................................................................................................\n" +
"\n" +
">> If a file name is not provided, the default file name is \n" +
"added and may be replaced on the next instance of \n" +
"encryption/decryption.\n" +
"\n" +
"..............................................................................................................\n" +
"\n" +
"Step 7: The logs section shows the recent actions made in \n" +
"the tool.");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        help.setText("Text Encrypter and Decrypter:\n" +
"===============================================\n" +
"Step 1: Enter the Simple text in Box 1.\n" +
"\n" +
"Step 2: The encrypted Text will be in Box 2\n" +
"\n" +
"Step 3: The Control Panel help to control the tool's actions.\n" +
"\n" +
"Step 4: Select the Algorithm to be used for\n" +
"encryption/decryption.\n" +
"\n" +
"Step 5: The Secret key field should be given the prefered key \n" +
"	for encryption.\n" +
"\n" +
"Step 6: The Clear button Clear all the Fields \n" +
"\n" +
"-----------------------------------------------------------------------------------\n" +
"\n" +
">>Secret Key should be of length of 8 - DES.\n" +
">>Secret Key should be of length of 16 - AES.\n" +
">>If a Secret Key is not provided by User,the default Key is \n" +
"  used.\n" +
"\n" +
"-----------------------------------------------------------------------------------\n");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jpb2.setValue(10);
        
        
        String algo = jcb1.getSelectedItem().toString();
        if("Select".equals(algo)){
                JOptionPane.showMessageDialog(null,"Please Select and algorithm to decrypt");
                jpb1.setValue(0);
            }
            else{

        if("AES".equals(algo))
        {
        try{
            byte k[] = null;
            String uk = uk1.getText();
            if(uk.equals("")){
                uk = "Aman-Kuvera1999!";
                k = uk.getBytes();
                jpb2.setValue(40);
            }
            else if(uk.length()!=16){
                jpb2.setValue(40);
                JOptionPane.showMessageDialog(null,"The key length for AES should be exactly 16");
                jpb2.setValue(0);
            }
            else{
                k= uk.getBytes();
                jpb2.setValue(40);
            }
            aesAlgo = new AesAlgorithm(k);
            DesAlgo = new DesAlgorithm(k);
            String plainText = jta1.getText();
            String encText = aesAlgo.encrypt(plainText);
            jpb2.setValue(90);
            jta2.setText(encText);
            JOptionPane.showMessageDialog(null,"Text Encrypted Successfully!");
            jpb2.setValue(0);
        }
        catch(Exception e){
            e.printStackTrace();
        }
        }
        
        else{
            
            try{
                byte k[] = null;
                String uk = uk1.getText();

                if(uk.equals("")){
                    uk = "Kuvera99";
                    k = uk.getBytes();
                    jpb2.setValue(40);
                }
                else if(uk.length()!=8){
                    JOptionPane.showMessageDialog(null,"The key length for DES should be exactly 8");
                    jpb2.setValue(0);
                }
                else{
                    k= uk.getBytes();
                    jpb2.setValue(40);
                }
                aesAlgo = new AesAlgorithm(k);
                DesAlgo = new DesAlgorithm(k);                
                String plainText = jta1.getText();
                String encText = DesAlgo.encrypt(plainText);
                jpb2.setValue(90);
                jta2.setText(encText);
                JOptionPane.showMessageDialog(null,"Text Encrypted Successfully!");
                jpb2.setValue(0);
                
            }
            catch(Exception e){
                e.printStackTrace();
            }
        }
        }
        
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       jpb2.setValue(10);
        String algo = jcb1.getSelectedItem().toString();
        if("Select".equals(algo)){
                JOptionPane.showMessageDialog(null,"Please Select and algorithm to decrypt");
                jpb1.setValue(0);
            }
            else{
        if("AES".equals(algo)){
        try{
            byte k[] = null;
            String uk = uk1.getText();
            if(uk.equals("")){
                uk = "Aman-Kuvera1999!";
                k = uk.getBytes();
                jpb2.setValue(40);
            }
            else if(uk.length()!=16){
                jpb2.setValue(40);
                JOptionPane.showMessageDialog(null,"The key length for AES should be exactly 16");
                jpb2.setValue(0);
            }
            else{
                k= uk.getBytes();
                jpb1.setValue(40);
            }
            aesAlgo = new AesAlgorithm(k);
            DesAlgo = new DesAlgorithm(k);
            String encryptedText = jta2.getText();
            String plainText = aesAlgo.decrypt(encryptedText);
            jpb2.setValue(90);
            jta2.setText(plainText);
            JOptionPane.showMessageDialog(null,"Text Decrypted Successfully!");
            jpb2.setValue(0);
        }catch(Exception e){

        }
        }
        else{
        
        try{
            byte k[] = null;
                String uk = uk1.getText();

                if(uk.equals("")){
                    uk = "Kuvera99";
                    k = uk.getBytes();
                    jpb2.setValue(40);
                }
                else if(uk.length()!=8){
                    JOptionPane.showMessageDialog(null,"The key length for DES should be exactly 8");
                    jpb2.setValue(0);
                }
                else{
                    k= uk.getBytes();
                    jpb2.setValue(40);
                }
                aesAlgo = new AesAlgorithm(k);
                DesAlgo = new DesAlgorithm(k);
            String encryptedText = jta2.getText();
            String plainText = DesAlgo.decrypt(encryptedText);
            jta2.setText(plainText);
            jpb2.setValue(90);
            JOptionPane.showMessageDialog(null,"Text Decrypted Successfully!");
            jpb2.setValue(0);
        }catch(Exception e){

        }
        }
        }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jta1.setText(null);
        jta2.setText(null);
        uk1.setText(null);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu2MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu2MenuSelected
        help.setText("----------------------------------- Contact Me -----------------------------------\n"+
                "\n"+"\n"+"\n"+"\n"+
                "                       LinkedIn Profile : \n"+
                "                       linkedin.com/in/aman-kuvera-11b17a175"+
                "\n"+"\n"+
                "                       Email : \n"+
                "                       kuveraaman1999@gmail.com"+
                "\n"
                );
    }//GEN-LAST:event_jMenu2MenuSelected

    private void jcb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Algorithm;
    private javax.swing.JTextField filePath;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JTextArea help;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JComboBox<String> jcb1;
    public javax.swing.JProgressBar jpb1;
    private javax.swing.JProgressBar jpb2;
    public javax.swing.JTextArea jta1;
    public javax.swing.JTextArea jta2;
    private javax.swing.JTextArea logsBox;
    private javax.swing.JTextField name;
    private javax.swing.JLabel preview;
    private javax.swing.JTextField secKey;
    private javax.swing.JTextField uk1;
    // End of variables declaration//GEN-END:variables
}
